apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deploy
spec:
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-container
          image: badi1298/kub-net-tasks:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
  replicas: 1
