apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: badi1298/kub-net-users:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: localhost
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
        - name: auth-container
          image: badi1298/kub-net-auth:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
  replicas: 1
